export const TOP_INDIAN_COLLEGES_BASE = [
  "GITA Autonomous College",
  "IIT Bombay",
  "IIT Delhi",
  "IIT Madras",
  "IIT Kanpur",
  "IIT Kharagpur",
  "IIT Roorkee",
  "IIT Guwahati",
  "IIT Hyderabad",
  "IIT BHU",
  "IIT Indore",
  "IIT Ropar",
  "IIT Gandhinagar",
  "IIT Bhubaneswar",
  "IIT Jodhpur",
  "IIT Patna",
  "IIT Mandi",
  "IIT Tirupati",
  "IIT Palakkad",
  "IIT Dhanbad",
  "NIT Trichy",
  "NIT Surathkal",
  "NIT Warangal",
  "NIT Rourkela",
  "NIT Calicut",
  "NIT Kurukshetra",
  "NIT Durgapur",
  "NIT Allahabad",
  "NIT Jaipur",
  "NIT Nagpur",
  "NIT Jalandhar",
  "NIT Silchar",
  "NIT Hamirpur",
  "NIT Patna",
  "NIT Raipur",
  "NIT Agartala",
  "BITS Pilani",
  "BITS Goa",
  "BITS Hyderabad",
  "IIIT Hyderabad",
  "IIIT Bangalore",
  "IIIT Delhi",
  "IIIT Allahabad",
  "IIIT Gwalior",
  "IIIT Lucknow",
  "IIIT Pune",
  "IIIT Kottayam",
  "Delhi Technological University",
  "Netaji Subhas University of Technology",
  "Jadavpur University",
  "VIT Vellore",
  "VIT Chennai",
  "SRM Institute of Science and Technology",
  "Manipal Institute of Technology",
  "Thapar Institute of Engineering and Technology",
  "RV College of Engineering",
  "PES University",
  "MS Ramaiah Institute of Technology",
  "BMS College of Engineering",
  "College of Engineering Pune",
  "Veermata Jijabai Technological Institute",
  "ICT Mumbai",
  "Anna University",
  "PSG College of Technology",
  "SSN College of Engineering",
  "Amrita Vishwa Vidyapeetham",
  "Nirma University",
  "DAIICT Gandhinagar",
  "Institute of Engineering and Technology Lucknow",
  "Bharati Vidyapeeth College of Engineering",
  "University Institute of Engineering and Technology Chandigarh",
  "Punjab Engineering College",
  "Indian Institute of Engineering Science and Technology Shibpur",
  "Jamia Millia Islamia",
  "Aligarh Muslim University",
  "Banaras Hindu University",
  "MNNIT Allahabad",
  "HBTU Kanpur",
  "Sardar Vallabhbhai National Institute of Technology",
  "Malaviya National Institute of Technology Jaipur",
  "Visvesvaraya National Institute of Technology Nagpur",
  "NIT Meghalaya",
  "NIT Sikkim",
  "NIT Mizoram",
  "NIT Manipur",
  "NIT Arunachal Pradesh",
  "NIT Uttarakhand",
  "NIT Andhra Pradesh",
  "NIT Delhi",
  "NIT Goa",
  "NIT Puducherry",
  "University of Hyderabad",
  "Savitribai Phule Pune University",
  "Calcutta University",
  "University of Delhi",
  "Jawaharlal Nehru University",
  "Osmania University",
  "Andhra University",
  "Cochin University of Science and Technology",
  "Maharaja Sayajirao University of Baroda",
  "Shiv Nadar University",
  "Ashoka University",
  "Kalinga Institute of Industrial Technology",
  "Siksha O Anusandhan",
  "Lovely Professional University",
  "Chandigarh University",
  "Amity University Noida",
  "UPES Dehradun",
  "Symbiosis Institute of Technology",
  "Maharashtra Institute of Technology Pune",
  "SASTRA Deemed University",
  "Koneru Lakshmaiah University",
  "GITAM University",
  "Jain University",
  "Christ University",
  "Galgotias University",
  "Noida Institute of Engineering and Technology",
  "KJ Somaiya College of Engineering",
  "Dwarkadas J Sanghvi College of Engineering",
  "Sardar Patel Institute of Technology",
  "Fr Conceicao Rodrigues College of Engineering",
  "Walchand College of Engineering",
  "Government College of Engineering Pune",
  "Government College of Engineering Karad",
  "Government College of Engineering Aurangabad",
  "Shri Ramdeobaba College of Engineering and Management",
  "Lakshmi Narain College of Technology Bhopal",
  "Medi-Caps University",
  "Rajiv Gandhi Proudyogiki Vishwavidyalaya",
  "Shri Govindram Seksaria Institute of Technology and Science",
  "NIT Srinagar",
  "NIT Hamirpur",
  "NIT Kurukshetra",
  "NIT Jamshedpur",
  "NIT Bhopal",
  "NIT Jaipur",
  "Birla Institute of Technology Mesra",
  "Birla Institute of Technology Patna",
  "IIT Jammu",
  "IIT Dharwad",
  "IIT Bhilai",
  "IIT Goa",
  "IIT (ISM) Dhanbad",
];

const STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

const PREFIXES = [
  "Government Engineering College",
  "State Institute of Technology",
  "National College of Engineering",
  "University Institute of Technology",
  "Autonomous Institute of Engineering",
  "College of Technology",
  "School of Computer Science and Engineering",
  "Institute of Science and Technology",
];

function buildColleges(target = 600) {
  const result = [...TOP_INDIAN_COLLEGES_BASE];
  let serial = 1;

  while (result.length < target) {
    const prefix = PREFIXES[(serial - 1) % PREFIXES.length];
    const state = STATES[(serial - 1) % STATES.length];
    const name = `${prefix} ${state} ${serial}`;

    if (!result.includes(name)) {
      result.push(name);
    }
    serial += 1;
  }

  return result.slice(0, target);
}

export const INDIAN_COLLEGES = buildColleges(600);

export const COURSE_OPTIONS = [
  "B.Tech",
  "M.Tech",
  "BCA",
  "MCA",
  "B.Sc Computer Science",
  "M.Sc Computer Science",
  "B.Tech AI",
  "B.Tech Data Science",
  "B.Tech Information Technology",
] as const;

export const YEAR_OPTIONS = ["2025", "2026", "2027", "2028", "2029"] as const;

export const BRANCH_OPTIONS = [
  "Computer Science Engineering",
  "Information Technology",
  "Artificial Intelligence",
  "Data Science",
  "Machine Learning",
  "Cyber Security",
  "Electronics Engineering",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
] as const;
